name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://allure.autotests.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 2227
      - uses: Xotabu4/selenoid-github-action@v2
      - run: allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: build/allure-results
#      - name: Copy History
#        uses: actions/checkout@v2
#        if: always()
#        with:
#          ref: gh-pages
#          path: gh-pages
#      - name: Build Report
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        with:
#          allure_results: build/allure-results
#          allure_history: allure-history
#          keep_reports: 20
#      - name: Publish Report
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history